print("Hola usuari@!")
nombre= input("ingrese su nombre")
nombreCap= nombre.capitalize()
print("Hola",nombreCap)
print("ingrese 5 palabras")
palabra1= input("ingrese palabra 1")
palabra2= input("ingrese palabra 2")
palabra3= input("ingrese palabra 3")
palabra4= input("ingrese palabra 4")
palabra5= input("ingrese palabra 5")
palabraA= palabra1.upper()
palabraB= palabra2.lower()
palabraNueva=palabraA + palabraB
print(palabraNueva)