frase= input("ingrese frase")
letra1= input("ingrese primer letra")
letra2= input("ingrese segunda letra")
letra3= input("ingrese tercer letra")
letra4= input("ingrese cuarta letra")
letra5= input("ingrese quinta letra")
frase1= frase.replace("a",letra1)
frase2= frase1.replace("e",letra2)
frase3=frase2.replace("i",letra3)
frase4= frase3.replace("u",letra4)
frase5=frase4.replace("o",letra5)
print(frase5)